### ISSUE TITLE
Your example doesent run anymore

### ISSUE THREAD

**Issue by nordfalk** [yamad/jaxrs-docker-example#1]
$ mvn install
...
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Internal error in the plugin manager executing goal 'org.wildfly.swarm:wildfly-swarm-plugin:2017.7.0:package': Unable to load the mojo 'org.wildfly.swarm:wildfly-swarm-plugin:2017.7.0:package' in the plugin 'org.wildfly.swarm:wildfly-swarm-plugin'. A required class is missing: Lorg/eclipse/aether/impl/ArtifactResolver;
org.eclipse.aether.impl.ArtifactResolver
...

I thinks its becaurse its now called https://thorntail.io/ instead of http://wildfly-swarm.io/

$ ls -l target/
totalt 11332
drwxrwxr-x 3 j j     4096 mar 14 15:40 classes
drwxrwxr-x 4 j j     4096 mar 14 15:40 forge-test
-rw-rw-r-- 1 j j 11582222 mar 14 15:44 forge-test.war
drwxrwxr-x 3 j j     4096 mar 14 15:40 generated-sources
drwxrwxr-x 2 j j     4096 mar 14 15:40 maven-archiver
drwxrwxr-x 2 j j     4096 mar 14 15:44 surefire

$ docker build -t rest-test .
Sending build context to Docker daemon     25MB
Step 1/4 : FROM openjdk:jre-alpine
jre-alpine: Pulling from library/openjdk
8e3ba11ec2a2: Pull complete 
311ad0da4533: Pull complete 
391a6a6b3651: Pull complete 
Digest: sha256:1bed44170948277881d88481ecbd07317eb7bae385560a9dd597bbfe02782766
Status: Downloaded newer image for openjdk:jre-alpine
 ---> ccfb0c83b2fe
Step 2/4 : COPY target/forge-test-swarm.jar /opt/forge-test-swarm.jar
COPY failed: stat /var/lib/docker/tmp/docker-builder781879719/target/forge-test-swarm.jar: no such file or directory

**Comment by yamad** [comment]
Thanks, I'll take a look. I didn't know about the name change.

**Comment by yamad** [comment]
thanks @nordfalk . seems to work now. at least it runs through and a server starts up and serves a hello world.
